name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install pandas pytest

      - name: Run extract
        working-directory: ./   # 👈 ensures we are inside repo root
        run: python extract.py

      - name: Run transform
        working-directory: ./   # 👈 same here
        run: python transform.py

      - name: Run load
        working-directory: ./   # 👈 and here
        run: python load.py

      - name: Run tests
        working-directory: ./tests
        run: pytest
